### ISSUE TITLE
qvc.qvs works in 12.10 but not in 12.40. Unknown statement error

### ISSUE THREAD

**Issue by sreeramulas** [RobWunderlich/Qlikview-Components#87]
Hi Experts,
We recently upgraded from 12.10 to 12.40 version of QlikView.

Below is the code that works fine in 12.10 but not in 12.40. It throws unknown statement error.

Your help here is highly appreciated.

Attached are the error messages that I receive and the actual qvc.qvs file that I use while generating the QVD's using the qvdGenerator.qvw. This generator uses an excel file to get the list of tables names and the load code.

//==========================================================//==========================================================// Execute the SQL Select.//==========================================================

[$(Qvc.Loader.v.Tablename)]: // vTablename is set by the IncrementalSetup routine.

Rem; // Fix syntax error from table label with variable // If LOAD Statement provided, use it

IF len('$(_qvctemp.den.loadStatement)')>0 THEN

    $(_qvctemp.den.loadStatement);

ELSE // No LOAD Statement, build a SQL SELECT 

       IF $(Qvc.Loader.v.CreateExtractTimestampField) THEN

                LOAD *, now(1) as ExtractTimestamp;

       ENDIF

       SQL SELECT $(_qvctemp.den.columns) FROM $(_qvctemp.den.table) WHERE $(Qvc.Loader.v.IncrementalExpression) //incrementalExpression is set up the Qvc.IncrementalSetup routine. ;

ENDIF
![Qlik 12 40 Error](https://user-images.githubusercontent.com/54297852/63311998-610d5680-c343-11e9-90e6-33775d72fa23.PNG)
[Qvc.zip](https://github.com/RobWunderlich/Qlikview-Components/files/3518349/Qvc.zip)

**Comment by RobWunderlich** [comment]
Fix to Qvc.DbExtract is available by using the repo copy here at Qvc_Runtime/qvc.qvs or script including with a web link: 
$(Must_Include=http://raw.githubusercontent.com/RobWunderlich/Qlikview-Components/master/Qvc_Runtime/Qvc.qvs);

I'll build this into a release later this week.

**Comment by sreeramulas** [comment]
Hi Rob,

Thanks heaps for your response and looking into the issue. Appreciate it.

I have copy pasted the code in the above link into the qvc.qvs file and I keep getting a pop up window to select the data source. Please find the attached pic.

Could you please advise what am I missing?

Thanks in advance.

**Comment by RobWunderlich** [comment]
Fixed in release V11.3

**Comment by sreeramulas** [comment]
[Qvc.zip](https://github.com/RobWunderlich/Qlikview-Components/files/3532740/Qvc.zip)

[DbExtract.zip](https://github.com/RobWunderlich/Qlikview-Components/files/3532742/DbExtract.zip)

Hi Rob,

Thank you for your quick update.
I have tried using the new qvc.qvs file in the link
https://github.com/RobWunderlich/Qlikview-Components/tree/master/Qvc_Runtime

I still get the pop up window asking the data source.
Please find attached files that I am using.

**Comment by RobWunderlich** [comment]
Can you try downloading and extracting the 11.3 release?

**Comment by sreeramulas** [comment]
Hi Rob,

Sorry for the delay in my response.
I have downloaded the whole component folder and tried but still it is the same and keeps asking me the Data source. The folder structure which I downloaded is intact.
Only changes I did is replace the sampleextractlist.xls with my file and the connection file with my file.

Rest all same and I do keep getting the pop up window asking 'Select Data Source'.

I really appreciate you taking helping me out Rob. Cheers.
